version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092

  # Сервисы
  producer:
    build: .
    environment:
      - KAFKA_BOOTSTRAP=kafka:9092
      - MODE=producer  # ← Явно
    depends_on:
      - kafka
    command: ["python", "producer_consumer.py"]

  consumer:
    build: .
    environment:
      - KAFKA_BOOTSTRAP=kafka:9092
      - MODE=consumer  # ← ЭТО ОБЯЗАТЕЛЬНО!
    depends_on:
      - kafka
    command: ["python", "producer_consumer.py"]

  test-producer:
    build: .
    environment:
      - KAFKA_BOOTSTRAP=kafka:9092
    depends_on:
      - kafka
    command: ["python", "test_producer.py"]

  partition-analyzer:
    build: .
    environment:
      - KAFKA_BOOTSTRAP=kafka:9092
    depends_on:
      - kafka
    command: ["python", "partition_analyzer.py"]

  dlq-checker:
    build: .
    environment:
      - KAFKA_BOOTSTRAP=kafka:9092
    depends_on:
      - kafka
    command: ["python", "dlq_checker.py"]